### ISSUE TITLE
Green mouse over

### ISSUE THREAD

**Issue by Nathanoid** [cdig/imagineering#3]
It sure would be nice to be able to do that green mouse over thing again in this new modern era.

**Comment by theseanzo** [comment]
I don't know what this is or what it means. Can you clarify or provide an example for me?

**Comment by Nathanoid** [comment]
Alrighty. 

In flash we have the ability to link multiple symbols together so that when you mouse over one of them they all get a green highlight on them. This allows us to go "See? See? These things are really the same!"

For example go to: 

https://www.lunchboxsessions.com/contents/mining--construction -> 24H Grader -> Combination Valve 2D

and mouse over the various valves.

**Comment by ivanreese** [comment]
The trick will be figuring out what it means, visually, for something to be in the "highlighted" state. There are filter effects you can use to (eg) tint things green, but they don't work in any version of IE.

For the acid project, Robyn made green versions of all her highlight-able images in Photoshop. That's a pain I'd like to salve.

**Comment by ivanreese** [comment]
Closing, because this exists in SVG Activity. If we need it in other contexts, then just mention that in Slack or file another issue.
