### ISSUE TITLE
Left, right, up and down Divs shaped like arrows

### ISSUE THREAD

**Issue by iMcKelvie** [cdig/imagineering#4]
Hi!

If anyone is bored, it would be cool to have divs that point. (including screenshot for an example)
I made this example by modifying code from cssarrowplease , but I'm not quite up to the task of making it scale nicely with CD map when I change sizes, etc. In a perfect world, the html to use this inside of cd-map might look something like:

`<cd-arrow-right pin right class="orange">Breather/Filler Cap</cd-arrow-right>`

![screen shot 2015-06-03 at 4 21 18 pm](https://cloud.githubusercontent.com/assets/7819612/7972790/a7a32074-0a0c-11e5-86e1-2f69f953c6ad.png)

**Comment by iMcKelvie** [comment]
so I see that my little html example did not work. Oh well.

**Comment by ivanreese** [comment]
Look again ;)

The trick to rendering HTML in markdown is to surround it with backticks.

Yeah, scaling arrows should be easily doable. I think they'd make a good challenge for someone other than me - an opportunity to assert your growing CSS mastery. If there are no takers by the time I get back, then I'll take a crack at it.

**Comment by iMcKelvie** [comment]
much nicer - thanks, Ivan!

**Comment by ivanreese** [comment]
Moved to: https://github.com/cdig/lbs-pack/issues/2
