### ISSUE TITLE
"We Recommend" for LBS modules

### ISSUE THREAD

**Issue by iMcKelvie** [cdig/imagineering#5]
Suggestion for Discussion 

When a user finishes a module, it might be nice to bring up a few suggestions for modules to tackle next. Could be as simple as a list, or one day, maybe we could do something cool (and GUI-er? Is that a term and am I using it correctly?) with those names. (I have the Ascendancy research tree in my head right now, but I'll bet there are a lot of neat solutions.)

If this idea is liked, even if there is no plan on how to implement it, it might be good to begin charting the relationships between these modules now, as we are developing them.

![screen shot 2015-06-16 at 9 01 16 am](https://cloud.githubusercontent.com/assets/7819612/8186254/6a6f6b28-1406-11e5-94b7-55b9cce95e25.png)

or 
![screen shot 2015-06-16 at 9 01 44 am](https://cloud.githubusercontent.com/assets/7819612/8186273/844c803a-1406-11e5-97b1-6af912d80719.png)

**Comment by ivanreese** [comment]
+1000

**Comment by ivanreese** [comment]
Moved to https://github.com/cdig/lunchboxsessions/wiki/Idea-Bucket
